export const DPT_N8_enums: [string, string, string, string, string][] = [
  ["20.001", "1 byte", "DPT_SCLOMode", "Enum", "{0=auto, 1=comfort, 2=standby}"],
  ["20.002", "1 byte", "DPT_BuildingMode", "Enum", "{0=in use, 1=not in use, 2=protection}"],
  ["20.003", "1 byte", "DPT_OccMode", "Enum", "{0=occupied, 1=standby, 2=not occupied, 3=protection}"],
  ["20.004", "1 byte", "DPT_Priority", "Enum", "{0=highest, 1=high, 2=medium, 3=lowest}"],
  ["20.005", "1 byte", "DPT_LightApplicationMode", "Enum", "{0=normal, 1=presence, 2=night round}"],
  ["20.006", "1 byte", "DPT_ArticleNo", "Enum", "[0 … 255] article number"],
  ["20.007", "1 byte", "DPT_PIControllerMode", "Enum", "{0=PI, 1=PID, 2=PD, 3=P-only, 4=manual}"],
  ["20.008", "1 byte", "DPT_WarpingMode", "Enum", "{0=neither, 1=heat only, 2=cool only, 3=both}"],
  ["20.010", "1 byte", "DPT_MediumType", "Enum", "{0=TP, 1=PL110, 2=RF, 3=KNX IP}"],
  ["20.011", "1 byte", "DPT_ErrorClass_System", "Enum", "[0 to 18] ErrorClass_System"],
  ["20.012", "1 byte", "DPT_ErrorClass_HVAC", "Enum", "[0 to 4] AlarmClass_HVAC"],
  ["20.013", "1 byte", "DPT_Time_Delay", "Enum", "[0 to 25] TimeDelay steps"],
  ["20.014", "1 byte", "DPT_Beaufort_Wind_Force_Scale", "Enum", "[0 to 12] Wind Force Scale"],
  ["20.017", "1 byte", "DPT_SensorSelect", "Enum", "[0 to 4] SensorSelect register"],
  ["20.020", "1 byte", "DPT_ActuatorConnectType", "Enum", "{0=direct, 1=via auxiliary control, 2=via system module}"],
  ["20.021", "1 byte", "DPT_Cloud_Cover", "Enum", "{0=clear, 1=fair, 2=partly cloudy, 3=cloudy, 4=overcast}"],
  ["20.022", "1 byte", "DPT_PowerReturnMode", "Enum", "{0=no action, 1=mode active after power return, 2=synchronized}"],
  ["20.100", "1 byte", "DPT_FuelType", "Enum", "{0=oil, 1=gas, 2=coal/wood, 3=electrical, 4=district heating, 5=solar}"],
  ["20.101", "1 byte", "DPT_BurnerType", "Enum", "{0=1-stage burner, 1=2-stage burner, 2=modulating burner}"],
  ["20.102", "1 byte", "DPT_HVACMode", "Enum", "{0=auto, 1=comfort, 2=standby, 3=economy, 4=protection}"],
  ["20.103", "1 byte", "DPT_DHWMode", "Enum", "{0=auto, 1=legionella protection, 2=normal DHW, 3=reduced DHW, 4=off}"],
  ["20.104", "1 byte", "DPT_LoadPriority", "Enum", "{0=none, 1=DHW load priority, 2=heating load priority, 3=both}"],
  ["20.105", "1 byte", "DPT_HVACContrMode", "Enum", "{0=auto, 1=heating, 2=warmup, 3=cooling, 4=cooldown, 5=night, 6=off}"],
  ["20.106", "1 byte", "DPT_HVACEmergMode", "Enum", "{0=normal, 1=emergency heat, 2=emergency cool, 3=shutoff/alarm}"],
  ["20.107", "1 byte", "DPT_ChangeoverMode", "Enum", "{0=auto, 1=cooling-only, 2=heating-only, 3=changeover}"],
  ["20.108", "1 byte", "DPT_ValveMode", "Enum", "{0=normal operation, 1=open ventilation, 2=closed, 3=safety state}"],
  ["20.109", "1 byte", "DPT_DamperMode", "Enum", "{0=normal, 1=fully open, 2=fully closed, 3=ventilation position}"],
  ["20.110", "1 byte", "DPT_HeaterMode", "Enum", "{0=comfort heater, 1=eco heater, 2=night setback}"],
  ["20.111", "1 byte", "DPT_FanMode", "Enum", "{0=auto fan, 1=continuous speed, 2=off, 3=manual speed override}"],
  ["20.112", "1 byte", "DPT_MasterSlaveMode", "Enum", "{0=independent master, 1=cooperating slave}"],
  ["20.113", "1 byte", "DPT_StatusRoomSetp", "Enum", "{0=no setpoint offset, 1=setpoint offset active}"],
  ["20.114", "1 byte", "DPT_MeteringDeviceType", "Enum", "{0=water meter, 1=electricity meter, 2=gas meter, 3=heat meter, 4-15=generic}"],
  ["20.115", "1 byte", "DPT_HumDehumMode", "Enum", "{0=controlled humidity, 1=humidification, 2=dehumidification, 3=off}"],
  ["20.120", "1 byte", "DPT_ADAType", "Enum", "{0=adaptive control off, 1=adaptive PI, 2=fully adaptive learning}"],
  ["20.121", "1 byte", "DPT_BackupMode", "Enum", "{0=no backup system, 1=standby reserve backup active}"],
  ["20.122", "1 byte", "DPT_StartSynchronization", "Enum", "{0=immediate start, 1=delayed/synchronized start}"],
  ["20.600", "1 byte", "DPT_Behaviour_Lock_Unlock", "Enum", "{0=off, 1=on, 2=no change, 3=parameter, 4=memory, 5=updated, 6=before locking}"],
  ["20.601", "1 byte", "DPT_Behaviour_Bus_Power_Up_Down", "Enum", "{0=off, 1=on, 2=no change, 3=parameter, 4=last (value before down)}"],
  ["20.602", "1 byte", "DPT_DALI_Fade_Time", "Enum", "[0 … 15] fade duration per standard DALI specification"],
  ["20.603", "1 byte", "DPT_BlinkingMode", "Enum", "{0=BlinkingDisabled, 1=WithoutAcknowledge, 2=BlinkingWithAcknowledge}"],
  ["20.604", "1 byte", "DPT_LightControlMode", "Enum", "{0=automatic light control, 1=manual light control}"],
  ["20.605", "1 byte", "DPT_SwitchPBModel", "Enum", "{0=one-key control, 1=two-key control, 2=toggle control}"],
  ["20.606", "1 byte", "DPT_PBAction_Lighting", "Enum", "{0=toggle, 1=on, 2=off, 3=dim up, 4=dim down, 5=step up, 6=step down, 7=recall scene}"],
  ["20.607", "1 byte", "DPT_DimmPBModel", "Enum", "{0=1 pushbutton dimming, 1=2 pushbutton dimming, 2=short/long click}"],
  ["20.608", "1 byte", "DPT_SwitchOnMode", "Enum", "{0=last value, 1=fixed to 100%, 2=custom value, 3=day/night responsive}"],
  ["20.609", "1 byte", "DPT_LoadTypeSet", "Enum", "{0=universal, 1=electronic transformer, 2=inductive, 3=LED, 4=fluorescent}"],
  ["20.610", "1 byte", "DPT_LoadTypeDetected", "Enum", "{0=none detected, 1=resistive, 2=capacitive, 3=inductive, 4=fault}"],
  ["20.611", "1 byte", "DPT_Converter_Test_Control", "Enum", "{0=start function test, 1=start duration test, 2=stop test, 3=reset test}"],
  ["20.612", "1 byte", "DPT_Converter_Control", "Enum", "{0=normal mode, 1=inhibit mode, 2=re-light block, 3=emergency mode force}"],
  ["20.613", "1 byte", "DPT_DALI_Fade_Rate", "Enum", "[1 … 15] fade rate per DALI IEC 62386"],
  ["20.801", "1 byte", "DPT_SABExceptBehaviour", "Enum", "{0=up, 1=down, 2=stop, 3=stepstop, 4=slave}"],
  ["20.802", "1 byte", "DPT_SABBehaviour", "Enum", "{0=no action, 1=move to top, 2=move to bottom, 3=stop blinds}"],
  ["20.803", "1 byte", "DPT_SSSBMode", "Enum", "{0=automatic control, 1=manual positioning, 2=safety lockout}"],
  ["20.804", "1 byte", "DPT_BlindsControlMode", "Enum", "{0=normal blind control, 1=slat adjustment only}"],
  ["20.1000", "1 byte", "DPT_CommMode", "Enum", "{0=standard TP1, 1=low power RF, 2=high speed IP}"],
  ["20.1001", "1 byte", "DPT_RF_ModeSelect", "Enum", "{0=RF ready state, 1=transmit only, 2=receive only, 3=biditest}"],
  ["20.1002", "1 byte", "DPT_RF_Medium", "Enum", "{0=RF Multi, 1=RF Ready}"],
  ["20.1003", "1 byte", "DPT_RF_FilterSelect", "Enum", "{0=bypass, 1=filter unconfigured, 2=filter dynamic, 3=block all}"],
  ["20.1004", "1 byte", "DPT_RF_MediumType", "Enum", "{0=RF Ready, 1=RF Multi, 2=RF standard compatible}"],
  ["20.1005", "1 byte", "DPT_PB_Function", "Enum", "{0=push-button switch, 1=shutter rocker, 2=dimmer, 3=scene}"],
  ["20.1200", "1 byte", "DPT_MBus_BreakerValState", "Enum", "{0=breaker closed, 1=breaker open, 2=breaker ready to close}"],
  ["20.1202", "1 byte", "DPT_Peak_Event_status", "Enum", "{0=no peak event active, 1=peak load shed active}"],
  ["20.1203", "1 byte", "DPT_Breaker_Status", "Enum", "{0=off, 1=on, 2=trip local, 3=trip telecontrol}"],
  ["20.1204", "1 byte", "DPT_TIC_ContractType", "Enum", "{0=blue contract, 1=unregulated contract, 2=tempo contract}"],
  ["20.1205", "1 byte", "DPT_PLC_Status", "Enum", "{0=disconnected, 1=connected, 2=searching, 3=error, 4=reconnecting}"],
  ["20.1206", "1 byte", "DPT_Peak_Event_Notice", "Enum", "{0=no notice, 1=pre-notice active, 2=notice active, 3=event completed}"],
  ["20.1207", "1 byte", "DPT_Peak_Event", "Enum", "{0=no event, 1=peak event level 1, 2=peak event level 2, 3=critical peak shed}"],
  ["20.1208", "1 byte", "DPT_TIC_Type", "Enum", "{0=historical TIC, 1=standard TIC, 2=short TIC, 3=extended TIC}"],
  ["20.1209", "1 byte", "DPT_Type_TIC_Channel", "Enum", "{0=single phase, 1=three phase, 2=producer phase, 3=custom}"]
];

export const DPT_bitfields_and_actions: [string, string, string, string, string][] = [
  ["21.001", "1 byte", "DPT_StatusGen", "Bitfield", "bits: 0=out of service, 1=fault, 2=overridden, 3=alarm"],
  ["21.002", "1 byte", "DPT_Device_Control", "Bitfield", "bit0: user-stop, bit1: auto-override, bit2: low-power, bit3-7: rsvd"],
  ["21.100", "1 byte", "DPT_HVAC_Force_Status", "Bitfield", "bit0: heating force, bit1: cooling force, bit2: fan force, bit3-7: rsvd"],
  ["21.101", "1 byte", "DPT_Status_RHC", "Bitfield", "bit0: heat active, bit1: cool active, bit2: pump, bit3: aux, bit4-7: rsvd"],
  ["21.102", "1 byte", "DPT_Status_SDHWC", "Bitfield", "bit0: Legionella protect, bit1: DHW pump, bit2: re-heater, bit3-7: rsvd"],
  ["21.103", "1 byte", "DPT_Status_RCC", "Bitfield", "bit0: zone active, bit1: eco active, bit2: window open, bit3-7: rsvd"],
  ["21.104", "1 byte", "DPT_FuelTypeSet", "Bitfield", "bit0: solid, bit1: liquid, bit2: gaseous, bit3: electric, bit4: solar, bit5: heat pump"],
  ["21.105", "1 byte", "DPT_StatusRCC", "Bitfield", "bit0: cooling, bit1: eco, bit2: window open, bit3: dew point control"],
  ["21.106", "1 byte", "DPT_StatusAHU", "Bitfield", "bit0: intake, bit1: exhaust, bit2: bypass, bit3: filter alarm, bit4: frost alarm"],
  ["21.601", "1 byte", "DPT_LightActuatorErrorInfo", "Bitfield", "bit0: ballast fault, bit1: lamp fault, bit2: short circuit, bit3: thermal overload"],
  ["21.1000", "1 byte", "DPT_RF_Info", "Bitfield", "bit0: low battery, bit1: tamper alarm, bit2: supervisory fault, bit3-7: rsvd"],
  ["21.1001", "1 byte", "DPT_RF_FilterInfo", "Bitfield", "bit0=DoA filtering, bit1=Serial Number filtering, bit2=Domain Address filtering"],
  ["21.1002", "1 byte", "DPT_Security_Report", "Bitfield", "bit0: auth failed, bit1: replay attack, bit2: sequence error, bit3: key expired"],
  ["21.1010", "1 byte", "DPT_Channel_Activation_8", "Bitfield", "bits 0–7: channels 1–8 active={0,1}"],
  ["21.1200", "1 byte", "DPT_VirtualDryContact", "Bitfield", "bit0-7: contact channels 1-8 open={0}/closed={1}"],
  ["21.1201", "1 byte", "DPT_Phases_Status", "Bitfield", "bit0: phase L1 ok, bit1: phase L2 ok, bit2: phase L3 ok, bit3-7: rsvd"],
  ["22.100", "2 bytes", "DPT_StatusDHWC", "Bitfield", "16 bits status: DHW heating active, solar load, legionella mode, boiler active etc."],
  ["22.101", "2 bytes", "DPT_StatusRHCC", "Bitfield", "16 bits status: Heating coil active, cooling coil active, fan stage active, etc."],
  ["22.1000", "2 bytes", "DPT_Media", "Bitfield", "16 bits status: transmission speed, media type TP, RF, IP, PL, etc."],
  ["22.1010", "2 bytes", "DPT_Channel_Activation_16", "Bitfield", "bits 0–15: channels 1–16 active={0,1}"],
  ["23.001", "2 bits", "DPT_OnOff_Action", "Enum", "{0=off, 1=on, 2=toggle, 3=reserved}"],
  ["23.002", "2 bits", "DPT_Alarm_Reaction", "Enum", "{0=no action, 1=alarm pos, 2=alarm+ack}"],
  ["23.003", "2 bits", "DPT_UpDown_Action", "Enum", "{0=no action, 1=move up, 2=move down, 3=toggle Up/Down}"],
  ["23.102", "2 bits", "DPT_HVAC_PB_Action", "Enum", "{0=heating on, 1=cooling on, 2=toggle Heat/Cool, 3=reserved}"]
];

export const DPT_strings_and_other: [string, string, string, string, string][] = [
  ["24.001", "variable", "DPT_VarString_8859_1", "String", "Variable-length ISO 8859-1 string, null-terminated"],
  ["25.1000", "1 byte", "DPT_DoubleNibble", "Unsigned", "Upper nibble=[0…15], Lower nibble=[0…15]"],
  ["26.001", "1 byte", "DPT_SceneInfo", "Composite", "bit7: reserved; bit6: learn flag {0,1}; bits 0-5: Scene number [0..63]"],
  ["27.001", "4 bytes", "DPT_CombinedInfoOnOff", "Bitfield", "16 masks + 16 values for on/off switching"],
  ["28.001", "variable", "DPT_UTF-8", "String", "Variable-length UTF-8 encoded string, null-terminated"],
  ["29.010", "8 bytes", "DPT_ActiveEnergy_V64", "Signed", "[-9.2e18 … 9.2e18] Wh"],
  ["29.011", "8 bytes", "DPT_ApparantEnergy_V64", "Signed", "[-9.2e18 … 9.2e18] VAh"],
  ["29.012", "8 bytes", "DPT_ReactiveEnergy_V64", "Signed", "[-9.2e18 … 9.2e18] VARh"],
  ["30.1010", "3 bytes", "DPT_Channel_Activation_24", "Bitfield", "24-bit channel mask, bits 0–23: channels 1–24 active={0,1}"],
  ["31.101", "3 bits", "DPT_PB_Action_HVAC_Extended", "Enum", "{0=auto, 1=comfort, 2=standby, 3=economy, 4=protect}"]
];
